from selenium.webdriver.common.by import By

class Buttons:

    REMOVE_ADDRESS_BUTTON_FROM = (By.XPATH, "(//button[contains(@class, 'close-button')])[1]")
    REMOVE_ADDRESS_BUTTON_TO = (By.XPATH, "(//button[contains(@class, 'close-button')])[2]")
    OPTIMAL_BUTTON = (By.XPATH, "//div[text()='Оптимальный']")
    FASTER_BUTTON = (By.XPATH, "//div[text()='Быстрый']")
    MYSELF_BUTTON = (By.XPATH, "//div[text()='Свой']")
    CAR_BUTTON = (By.XPATH, "//div[contains(@class,'type')]//img[contains(@src,'car-active') or contains(@src,'/car.')]")
    WALK_BUTTON = (By.XPATH, "//div[contains(@class,'type')]//img[contains(@src,'/walk')]")
    TAXI_BUTTON = (By.XPATH, "//div[contains(@class,'type')]//img[contains(@src,'/taxi')]")
    BIKE_BUTTON = (By.XPATH, "//div[contains(@class,'type')]//img[contains(@src,'/bike')]")
    SCOOTER_BUTTON = (By.XPATH, "//div[contains(@class,'type')]//img[contains(@src,'/scooter')]")
    DRIVE_BUTTON = (By.XPATH, "//div[contains(@class,'type')]//img[contains(@src,'/drive') and not(contains(@src,'carsharing'))]")
    GET_ORDER_TAXI = (By.XPATH, "//button[text()='Вызвать такси']")
    RENT_CAR_TAXI = (By.XPATH, "//button[text()='Забронировать']")
    WORK_CAR_BUTTON = (By.XPATH, "//div[contains(@class,'tcard-title') and text()='Рабочий']")    
    SON_CAR_BUTTON = (By.XPATH, "//div[contains(@class,'tcard-title') and text()='Сонный']")
    VACATION_CAR_BUTTON = (By.XPATH, "//div[contains(@class,'tcard-title') and text()='Отпускной']")
    TALK_CAR_BUTTON = (By.XPATH, "//div[contains(@class,'tcard-title') and text()='Разговорчивый']")
    COMFORT_CAR_BUTTON = (By.XPATH, "//div[contains(@class,'tcard-title') and text()='Утешительный']")
    GLAMOUR_CAR_BUTTON = (By.XPATH, "//div[contains(@class,'tcard-title') and text()='Глянцевый']")
    CREATE_ORDER_BUTTON = (By.XPATH, "//button[contains(., 'Ввести номер и заказать')]")
    DETAILS_BUTTON = (By.XPATH, "//div[text()='Детали']/preceding-sibling::button")
    CANCEL_BUTTON = (By.XPATH, "//div[text()='Отменить']")


class Elements_check:

    MENU_PAGE = (By.CLASS_NAME, "workflow")
    MAP_PAGE = (By.CLASS_NAME, "app")
    MAP_ADDRESS = (By.CLASS_NAME, "dst-picker")
    ADDRESS_CONTAINER_FROM = (By.XPATH, "(//div[contains(@class, 'input-container')]//input)[1]")
    ADDRESS_CONTAINER_TO = (By.XPATH, "(//div[contains(@class, 'input-container')]//input)[2]")
    TOCHKA_A = (By.CSS_SELECTOR, "[class*='route-pin__label-a']")
    TOCHKA_B = (By.CSS_SELECTOR, "[class*='route-pin__label-b']")
    ROUTE_CONTAINER = (By.CSS_SELECTOR, ".route-selector")
    ROUTE_CARD = (By.CSS_SELECTOR, ".route-card")
    DISTANCE = (By.CSS_SELECTOR, ".route-distance")
    DURATION = (By.CSS_SELECTOR, ".route-duration")
    SELECT_BUTTON = (By.CSS_SELECTOR, ".route-card button")
    SELECT_ROUTE = (By.CSS_SELECTOR, ".workflow-subcontainer")
    AMOUNT_ROUTE = (By.XPATH,"(//div[contains(@class, 'results-text')]//div[contains(@class, 'text')])")
    TIME_ROUTE = (By.XPATH,"(//div[contains(@class, 'results-text')]//div[contains(@class, 'duration')])")
    PHONE_NUMBER_TAB = (By.XPATH, "//div[text()='Телефон']")
    PAYMENT_METHOD_TAB = (By.XPATH, "(//div[text()='Способ оплаты'])[2]")
    COMMENT_TAB = (By.XPATH, "//input[@name='comment']")
    ORDER_REQUIREMENTS_TAB = (By.XPATH, "//div[text()='Требования к заказу']")
    CHOOSE_TARIFF = (By.CSS_SELECTOR, ".tariff-cards")
    ACTIVE_TARIFF = (By.CSS_SELECTOR, ".tcard.active")
    ICON_ICON = (By.CSS_SELECTOR, ".tcard.active button.i-button.tcard-i")
    TARIFF_TOOLTIP = (By.CSS_SELECTOR, "div.__react_component_tooltip")
    TOOLTIP_ID = (By.ID, "tooltip_id")
    NOTEPAD_TAB = (By.CSS_SELECTOR, ".r-sw-label")
    NOTEPAD_CHECKBOKS = (By.XPATH,"//div[contains(@class,'r-sw-label') and text()='Столик для ноутбука']")
    WAIT_CAR_TAB = (By.XPATH, "//div[contains(@class,'order-body')]")
    NUMBER_CAR = (By.XPATH, "//div[contains(@class,'order-number')]")
    DATA_NUMBER = (By.XPATH, "//div[contains(@class,'order-button')]")
    RATING_DRIVER = (By.XPATH, "//div[contains(@class,'order-btn-rating')]")
    AMOUNT_TAXI_TAB = (By.XPATH, "//div[contains(@class,'o-d-sh') and contains(.,'Стоимость')]")
    FIND_CAR_TAB = (By.XPATH, "//div[contains(@class,'order-header-title') and text()='Поиск машины']")
    TIMER_TAB = (By.XPATH, "//div[contains(@class,'order-header-time')]")
    WAIT_TIMER_TAXI_TAB = (By.XPATH, "//div[contains(@class,'order-header-title') and contains(.,'приедет')]")
    DESCRIBE_TAXI_TAB = (By.XPATH, "//div[contains(@class,'order-subbody')]")
    TYPE_PAYMENT = (By.XPATH, "//div[contains(@class,'o-d-sh') and text()='Способ оплаты']/preceding-sibling::div[contains(@class,'o-d-h')]")
    DESCRIBE_DETAILS_TAB = (By.XPATH, "//div[contains(@class,'order-details-row')]")
    TAB_REQUIREMENT = (By.XPATH, "//div[contains(@class,'r-sw-container')]")
